# Generated by Django 3.1.3 on 2022-10-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_product_imgfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
