# Generated by Django 3.1.3 on 2022-10-20 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
    ]
