# Generated by Django 3.1.3 on 2022-10-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_product_imgfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imgfile',
        ),
    ]
