# Generated by Django 3.1.3 on 2022-10-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_product_imgfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=50)),
                ('contents', models.TextField()),
            ],
        ),
    ]
